### ISSUE TITLE
error when opening the master file in an IDE

### ISSUE THREAD

**Issue by BartBanaan** [Gaider10/PlayerHealthIndicators#16]
[{
	"resource": "/C:/Users/Bart/Desktop/PlayerHealthIndicators-master/",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "0",
	"severity": 8,
	"message": "The project was not built since its build path is incomplete. Cannot find the class file for net.minecraft.client.option.KeyBinding. Fix the build path then try building this project",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by Gaider10** [comment]
That's probably a problem with your ide
