### ISSUE TITLE
a option to increase space between player and health indicator

### ISSUE THREAD

**Issue by keremyurekli** [Gaider10/PlayerHealthIndicators#9]
in some servers health indicator overlaps with player name, so i think you can solve this issue by adding a option to increase gap between player and health indicator.
![2022-08-20_18 03 33](https://user-images.githubusercontent.com/85027678/185753393-55c884c1-1166-4e30-b6e7-f645cb067951.png)

**Comment by Gaider10** [comment]
Added in 1.1.0
